Armorial: analyse.TesteurExpression Class Reference
analyse.TesteurExpression Class Reference
Static Public Member Functions
static boolean EstUneCouleur (String[] exp, int position)
static boolean EstDuMeme (String[] exp, int position)
static boolean EstUnePartition (String[] exp, int position)
static boolean EstUnePartitionArme (String[] exp, int position)
static boolean EstUnePartitionChamp (String[] exp, int position)
static boolean EstPlein (String[] exp, int position)
static boolean EstUneCharge (String[] exp, int position)
static boolean EstUnePiece (String[] exp, int position)
static boolean EstUnMeuble (String[] exp, int position)
static boolean EstLeToutCouleur (String[] exp, int position)
static boolean EstAccompagne (String[] exp, int position)
static boolean EstUnOrdre (String[] exp, int position)
Detailed Description
Classe utilitaire fournissant des outils permettant de déterminer si des expressions font références à des structures connues.
Definition at line 10 of file TesteurExpression.java.
Member Function Documentation
EstAccompagne()
static boolean analyse.TesteurExpression.EstAccompagne (String[] exp, int position) static
Test si l'expression courante est une expression d'accompagnement
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true l'exp est un accompagnement
Definition at line 344 of file TesteurExpression.java.
EstDuMeme()
static boolean analyse.TesteurExpression.EstDuMeme (String[] exp, int position) static
Test si l'expression courante est "du même"
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true l'exp est "du même"
Definition at line 67 of file TesteurExpression.java.
EstLeToutCouleur()
static boolean analyse.TesteurExpression.EstLeToutCouleur (String[] exp, int position) static
Test si l'expression courante est "le tout" coloré
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true l'exp est "le tout" coloré
Definition at line 320 of file TesteurExpression.java.
EstPlein()
static boolean analyse.TesteurExpression.EstPlein (String[] exp, int position) static
Test de "plein"
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true l'exp "plein" est trouvée
Definition at line 154 of file TesteurExpression.java.
EstUneCharge()
static boolean analyse.TesteurExpression.EstUneCharge (String[] exp, int position) static
Test de charge
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true l'exp est une charge, défini la position à la fin de la charge
Definition at line 174 of file TesteurExpression.java.
References analyse.TesteurExpression.EstUnePiece(), and analyse.TesteurExpression.EstUnMeuble().
EstUneCouleur()
static boolean analyse.TesteurExpression.EstUneCouleur (String[] exp, int position) static
Test de couleur,
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true si une couleur est reconnue, false sinon
Definition at line 22 of file TesteurExpression.java.
References structures.Couleur.getCouleur().
Referenced by analyse.TesteurExpression.EstUnePartitionChamp().
EstUnePartition()
static boolean analyse.TesteurExpression.EstUnePartition (String[] exp, int position) static
Test de partition
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true si une partition est reconnue, false sinon
Definition at line 91 of file TesteurExpression.java.
References structures.Partition.GetPartition().
Referenced by analyse.TesteurExpression.EstUnePartitionChamp().
EstUnePartitionArme()
static boolean analyse.TesteurExpression.EstUnePartitionArme (String[] exp, int position) static
Test de partition relative à une arme
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true si une partition est reconnue, false sinon
Definition at line 116 of file TesteurExpression.java.
References analyse.TesteurExpression.EstUnePartitionChamp().
EstUnePartitionChamp()
static boolean analyse.TesteurExpression.EstUnePartitionChamp (String[] exp, int position) static
Test de partition relative à un champ
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true si une partition est reconnue, false sinon
Definition at line 129 of file TesteurExpression.java.
References analyse.TesteurExpression.EstUneCouleur(), and analyse.TesteurExpression.EstUnePartition().
Referenced by analyse.TesteurExpression.EstUnePartitionArme().
EstUnePiece()
static boolean analyse.TesteurExpression.EstUnePiece (String[] exp, int position) static
Test de piece
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true l'exp est une piece, la position est définie après l'article
Definition at line 243 of file TesteurExpression.java.
Referenced by analyse.TesteurExpression.EstUneCharge().
EstUnMeuble()
static boolean analyse.TesteurExpression.EstUnMeuble (String[] exp, int position) static
Test de meuble
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true l'exp est un meuble, la position est définie après l'article
Definition at line 279 of file TesteurExpression.java.
Referenced by analyse.TesteurExpression.EstUneCharge().
EstUnOrdre()
static boolean analyse.TesteurExpression.EstUnOrdre (String[] exp, int position) static
Test d'ordre (par ex : "en 1 et 4")
Parameters
exp,expression complète
position,position de l'élément à analyser dans l'expression
Returns
true si un ordre est reconnue, false sinon
Definition at line 365 of file TesteurExpression.java.
The documentation for this class was generated from the following file:
src/main/java/analyse/TesteurExpression.java